services:
  qrcode-app:
    image: nginx:alpine
    container_name: qrcode-generator
    restart: unless-stopped
    ports:
      - '3001:80'
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxynet

networks:
  proxynet:
    external: true
